### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by demmer** [juttle/juttle-engine#7]
Tracking issue for release 0.2.0, i.e. the initial public release of this package. The previously published 0.1.0 release is actually the juttle-service before the names changed.

* [x] Add a README with screenshot [#10]
* [x] Include all current adapters [#6]
* [x] Include a released version of juttle-viewer [#11]
* [x] Add CHANGELOG
* [x] Add juttle-engine-client script [#15]
* [x] Add basic app functional tests [#14]
